name: MeliProcess
options:
  minimumXcodeGenVersion: 2.0
  groupSortPosition: top
  generateEmptyDirectories: true
  bundleIdPrefix: com.gbrlcm.processoseletivo
  deploymentTarget:
    iOS: "15.0"
settings:
    DEVELOPMENT_TEAM: WK7599VNDW
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.0.1
localPackages:
  - ./Modules/Home
  - ./Modules/DesignSystem
  - ./Modules/Model
  - ./Modules/Search
  - ./Modules/Detail
  - ./Modules/Network
  - ./Modules/Router
  - ./Modules/RouterInterface
targets:
    App:
        type: application
        platform: iOS
        sources:
            - path: App
        dependencies:
            - package: Home
            - package: Router
        scheme:
            gatherCoverageData: true
            testTargets:
                - package: Home/HomeTests
                - package: Model/ModelTests
                - package: DesignSystem/DesignSystemTests
                - package: Search/SearchTests
                - package: Detail/DetailTests
                - package: Network/NetworkTests
                - package: Router/RouterTests
                - package: RouterInterface/RouterInterfaceTests
        
